CREATE TABLE USUARIOS (
    ID_USUARIO INT NOT NULL,

    EMAIL VARCHAR(50) NOT NULL,

    NOME VARCHAR(50) NOT NULL,
    SOBRENOME VARCHAR(50) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    CPF VARCHAR(11) NOT NULL,

    USER_NAME VARCHAR(50) NOT NULL,
    USER_PASSWORD VARCHAR(16) NOT NULL,

    KEYMASTER VARCHAR(50) NOT NULL,

    ULTIMO_IP VARCHAR(16) NOT NULL,
    ULTIMO_ACESSO DATE NOT NULL,

    ATIVO BOOLEAN NOT NULL,
    DT_CRIACAO DATE NOT NULL,
    DT_ATUALIZACAO DATE NOT NULL,

    PRIMARY KEY (ID_USUARIO)
)
CREATE TABLE ENDERECO_USUARIO(
    ID_ENDERECO INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    CEP VARCHAR(10) NOT NULL,
    SETOR VARCHAR(50) NOT NULL,
    COMPLEMENTO VARCHAR(50) NOT NULL,
    NUMERO_CONTATO VARCHAR(11) NOT NULL,
    PRIMARY KEY(ID_ENDERECO),
    FOREIGN KEY(ID_USUARIO)
)