CREATE TABLE IF NOT EXISTS pizza (
    ID SERIAL PRIMARY KEY,
    INGREDIENTES VARCHAR(255),
    ID_CARDAPIO INTEGER,

    CONSTRAINT fk_cardapio_pizza
    FOREIGN KEY (ID_CARDAPIO)
    REFERENCES cardapio(ID_CARDAPIO)
);
